version: '3.8'

services: 
  #Backend API
  backend-api: 
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart
    ports: 
      - "3000:3000"
    volumes:
        - ./:/usr/src/smart

  # Postgres API
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"